export default function handler(req, res) {
    const { title } = req.query;

    // Replace with the correct pre-signed URL for each video
    const videoUrls = {
        'Series_first': [
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/output.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s1-e2-reencoded.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s1-e3-reencoded.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s1-e4-reencoded.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s1-e5-reencoded.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s1-e6-reencoded.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s1-e7-reencoded.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s1-e8-reencoded.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s1-e9-reencoded.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s1-e10-reencoded.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s1-e11-reencoded.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s1-e12-reencoded.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s1-e13-reencoded.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s1-e14-reencoded.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s1-e15-reencoded.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s1-e16-reencoded.mp4',
            // Add more episode URLs for Series_first
        ],
        'Series_second': [
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e1.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e2.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e3.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e4.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e5.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e6.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e7.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e8.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e9.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e10.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e11.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e12.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e13.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e14.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e15.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e16.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e17.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e18.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e19.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e20.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e21.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e22.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e23.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e24.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e25.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e26.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e27.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e28.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e29.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e30.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e31.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e32.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e33.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e34.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e35.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e36.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e37.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e38.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-e39.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s2-40.mp4',
            // Add more episode URLs for Series_second
        ],
        'Series_third': [
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e1-n.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e2-n.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e3_h264.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e4_h264.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e5_h264.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e6_h264.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e7_h264.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e8_h264.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e9_h264.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e10_h264.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e11_h264.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e12_h264.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e13_h264.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e14_h264.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e15_h264.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s3-e16_h264.mp4',
        ],
        'Series_fourth': [
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com//s4-e1.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s4-e2.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s4-e3.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s4-e4.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s4-e5.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s4-e6.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s4-e7.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s4-e8.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s4-e9.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s4-e10.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s4-e11.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s4-e12.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s4-e13.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s4-e14.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s4-e15.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s4-e16.mp4',
        ],
        'Series_fifth': [
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e1.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e2.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e3.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e4.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e5.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e6.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e7.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e8.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e9.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e10.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e11.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e12.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e13.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e14.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e15.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s5-e16.mp4',
        ],
        'Series_sixth': [
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s6-e1.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s6-e2.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s6-e3.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s6-e4.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s6-e5.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s6-e6.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s6-e7.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s6-e8.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s6-e9.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s6-e10.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s6-e11.mp4',
            'https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/s6-e12.mp4',
        ]
    };

    if (!videoUrls[title]) {
        res.status(404).json({ message: 'Title not found' });
        return;
    }

    const episodes = videoUrls[title].map((videoUrl, index) => ({
        video: videoUrl,
        subtitle: `https://my-video-bucket-11.s3.eu-north-1.amazonaws.com/${title}-e${index + 1}.en.srt`, // Subtitle URL
        episode: `Episode ${index + 1}`
    }));

    res.status(200).json(episodes);
}